Visualize files revamp
rvankoert/loghi-htr pull request #11
Opened 2023-11-27 07:55 UTC by Thelukepet

- Refactored old visualize files & made them independent of data loaders / utils files, dark/light-mode support

- **Time-step prediction visualizer** takes top-3 most probable character for time-step, generates CTC encoding table, pre-processes "invisible" or unknown characters.

-  **Filter activations visualizer:** plots conv layer activations on top of input sample image, plots conv layer activations when provided with a random noise image, accounts for models of different channels / sample image shapes

- PDF combiner that creates a single sheet of the created visualizers 

- **vis_arg_parser:** used for processing user arguments in the terminal similar to how loghi-htr processes arguments.

- README instructions

2023-11-27 13:02 UTC, TimKoornstra requested changes
Ziet er over het algemeen prima uit. Zie wel een aantal comments. Vooral belangrijk om geen dingen in een file te zetten die geimporteerd kunnen worden - liefst alles daar binnen een functie of een `if __name__=="__main__"`.

Misschien kun je ook nog type hints en docstrings toevoegen? En op een aantal plekken wat extra comments om het wat makkelijker te kunnen volgen.

In je `visualize_filters_` files doe je soms dingen dubbel. Misschien kun je daar functies van maken die allebei de files kunnen gebruiken?

2023-11-27 13:02 UTC, TimKoornstra commented on README.md
>  5. [Frequently Asked Questions (FAQ)](#FAQ)
6.

2023-11-27 13:02 UTC, TimKoornstra commented on README.md
> +### 1. Visualize setup
Witregel na headers

2023-11-27 13:02 UTC, TimKoornstra commented on README.md
> +```
Ook voor en na block quotes en code blocks een witregel

2023-11-27 13:02 UTC, TimKoornstra commented on README.md
> +2. **visualize_filter_activations**: Display what the convolutional filters have learned after providing it with random noise + show the activation of conv filters for the `sample_image`. Each unique
Hier hoeft het dan weer niet ;)

2023-11-27 13:02 UTC, TimKoornstra commented on README.md
> +* a `sample_image_preds.csv` which consist of a character prediction table for each prediction timestep. The highest probability is the character that was chosen by the model
A

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/main.py
> +from fpdf import FPDF
Waar komt dit vandaan?

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/main.py
> +                      border=1)
Dit moet niet in de `if __name__`. In ieder geval er buiten en eigenlijk in een aparte file

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/vis_arg_parser.py
> +                                                                                               "the cost of performace")
De help iets beter alignen ;)

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +    main()
Ik ben geen fan van dingen buiten de `if __name__` of een functie te zetten, omdat bij elke import de hele file "uitgevoerd" wordt. Je kunt dus in je `main.py` allemaal onvoorziene side effects krijgen.

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +    exit(1)
Niet exiten, maar een nette error geven

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +from model import CERMetric, WERMetric, CTCLoss
Twee dingen:

- Eigenlijk moeten alle imports bovenaan de file staan. Met andere woorden: de sys.path.append mag hier niet tussen staan. Je kunt het beter even 1 keer importen bij de juiste functie.
- Dit houdt geen rekening met een user die deze file vanuit de root van het project wil runnen. Je kunt beter het volledige path gebruiken.

Volgens mij is er van alle twee de punten een voorbeeld bij de unittests.

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +    model = tf.keras.models.load_model(MODEL_PATH)
Kan ook: `model = tf.keras.models.load_model(MODEL_PATH, custom_objects={"CERMetric": CERMetric, ...}`
Moet ook nog ResidualBlock bij

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +    print(model.summary())
`model.summary()` print uit zichzelf al. De extra print zorgt voor een extra None output

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +        layer_list = conv_layer_list
Dit lijkt me makkelijker te kunnen?

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +            continue
`layer_list` kan alleen maar conv layers bevatten

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +                                     fontsize=20)
Mooier met f-string (dan hoef je ook niet te string casten)

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_timestep_predictions.py
> +os.environ["CUDA_VISIBLE_DEVICES"] = "0"
Je zegt hier "disable GPU", maar `CUDA_VISIBLE_DEVICES` geeft aan dat je 1 GPU selecteert

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_timestep_predictions.py
> +tf.keras.utils.get_custom_objects().update({"CTCLoss": CTCLoss})
Allemaal vergelijkbare code als in `visualize_filters_activations.py`. Misschien kun je meer code in functies opsplitsen die je in beide files kunt gebruiken?

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_timestep_predictions.py
> +    if '' in char_list:
Is dit mogelijk? Je leest de char_list uit een file, maar '' is geen karakter toch?

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_timestep_predictions.py
> +        end_point = (int(line_start), tf.get_static_value(image_height) + 50)
Is `line_start` niet al een int? Hierboven tel je er namelijk al iets bij op (of is het een float?)

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_timestep_predictions.py
> +            tensor_data.append(time_step.tolist())
Enumerate bij allebei niet nodig

2023-11-27 13:02 UTC, TimKoornstra commented on src/visualize/visualize_timestep_predictions.py
> +def main():
Kun je deze functie opsplitsen in meerdere functies? Hij is namelijk heel erg lang

2023-11-29 12:12 UTC, Thelukepet commented on src/visualize/visualize_timestep_predictions.py
> +        end_point = (int(line_start), tf.get_static_value(image_height) + 50)
line_start is een float ja

2023-11-30 08:16 UTC, Thelukepet commented
Changes made

2023-11-30 09:17 UTC, TimKoornstra requested changes
Nice! Al veel beter dan vorige keer. Paar kleine dingetjes nog en dan is ie af

2023-11-30 09:17 UTC, TimKoornstra commented on README.md
> +### 3. (Optional parameters)
Nog 1 witregel, dan is deze file goed :)

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/vis_utils.py
> +def prep_image_for_model(img_path, model_channels):
Kun je hier ook nog de type hint zetten? Dus `(img_path: str, model_channels: int) -> tuple[np.ndarray, tf.Tensor, tf.Tensor]`

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/vis_utils.py
> +    return img, image_width, image_height
Zo doe ik het in de API:

```python
    image = tf.io.decode_jpeg(image_bytes, channels=num_channels)

    # Resize while preserving aspect ratio
    target_height = 64
    aspect_ratio = tf.shape(image)[1] / tf.shape(image)[0]
    target_width = tf.cast(target_height * aspect_ratio, tf.int32)
    image = tf.image.resize(image,
                            [target_height, target_width])

    image = tf.image.resize_with_pad(image,
                                     target_height,
                                     target_width + 50)

    # Normalize the image and something else
    image = 0.5 - (image / 255)

    # Transpose the image
    image = tf.transpose(image, perm=[1, 0, 2])

    return image
``` 

Maar misschien werkt het niet hier hoor. Volgens mij zijn er wat dingen overbodig in de method van de `data_generator`. Het lezen van de image moet wel zoals je al had

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/vis_utils.py
> +    GPU = args.gpu
Constants (variabelen met hoofdletters) zijn niet nodig als je ze alleen in een functie gebruikt.

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +    in a convolutional layer using gradient ascent.
Kan ook gewoon bovenaan in de dosctring

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +    if args.do_detailed:
Zou je dit misschien als parameter mee kunnen geven? Is iets netter dan uit het luchtledige een arg grijpen

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +    if args.do_detailed:
En misschien zou ik de if en else omdraaien, maar dat is een persoonlijk iets

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +                sub_list_indices.append(i)
Waarom voeg je niet meteen de juiste `layer_info` toe aan een lijst? Dan hoef je hierna niet nog een list comprehension te doen

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +                  for layer in model.layers if layer.name.lower().startswith("conv")]
1 spatie extra

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +    conv_layer_list = [layer for layer in model.layers if layer.name.lower().startswith("conv")]
Deze lijst heb je al verzameld bij `select_number_of_row_plots`. Je kunt dit het beste doen _voor_ die functie en meegeven als parameter

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +                if args.sample_image:
Kan deze arg iets duidelijkere naam hebben? sample_image_path oid

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +                    loss, img = visualize_filter(random_filter_indices[filter_index],
Variabelen die je niet gebruikt na unpacken kun je ook aangeven met _. Dus `_, img = ...`

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +                                     f"{layer_info_dict.get('kernel_size')} : filters: "
Spatie voor :

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +        # output_dir = args.output
Kan weg

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/visualize_timestep_predictions.py
> +    # output_dir = args.output
:(

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/visualize_timestep_predictions.py
> +        os.makedirs(Path(__file__).with_name("visualize_plots"))
Kan ook met `os.makedirs(path, exist_ok=True)`

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/PdfMaker.py
> +from fpdf import FPDF
Staat dit in de `requirements.txt`?

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/PdfMaker.py
> +    MAX_HEIGHT = 1240
Liever in een `__init__` functie

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/PdfMaker.py
> +    MAX_HEIGHT = 1240
Maar omdat het constants zijn vind ik het goed

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/PdfMaker.py
Geen docstrings of type annotations :cry:

2023-11-30 09:17 UTC, TimKoornstra commented on src/visualize/main.py
> +    visualize_filters_activations.main()
Zou je hier in ieder geval args aan mee kunnen geven op een bepaalde manier?

2023-12-05 08:47 UTC, TimKoornstra requested changes

2023-12-05 08:47 UTC, TimKoornstra commented on src/data_generator.py
> +                raise ValueError("Invalid number of channels. Supported values are 1, 3, or 4.")
Must support 2 channel

2023-12-05 08:47 UTC, TimKoornstra commented on src/data_generator.py
> +                raise ValueError("Invalid number of channels. Supported values are 1, 3, or 4.")
of
`raise NotImplementedError()`

2023-12-05 08:47 UTC, TimKoornstra commented on src/visualize/vis_utils.py
> +
rm

2023-12-05 08:47 UTC, TimKoornstra commented on src/visualize/visualize_filters_activations.py
> +os.environ['TF_DETERMINISTIC_OPS'] = '0'
voor TF import

2023-12-05 08:47 UTC, TimKoornstra commented on src/visualize/visualize_timestep_predictions.py
> +        pad_steps_skip = np.floor(50 / step_width)
50 // step_width

2023-12-05 08:47 UTC, TimKoornstra commented on src/visualize/visualize_timestep_predictions.py
type hints

2023-12-11 08:27 UTC, Thelukepet commented on src/data_generator.py
> +                raise ValueError("Invalid number of channels. Supported values are 1, 3, or 4.")
Added NotImplementedError()

2023-12-11 08:54 UTC, TimKoornstra approved these changes

2023-12-12 14:37 UTC, merged