V1 DataGenerator and Data Augment Revamp on GPU ( no unittest updates)
rvankoert/loghi-htr pull request #21
Opened 2024-01-17 16:14 UTC by Thelukepet

_(continuation from cv2-tfm-replacement branch)_
- Refactored CPU (cv2) / deprecated image manipulation packages (TFA)

- Refactored data augmentations to be part of the final Sequential model for GPU support, this happens within the `customize_model` function of `management.py`
   - Dynamic handling of subsequent data augments and different number of channels (1, 3 or 4)
   - Custom keras Layer classes for each type of augmentation, can be easily extended in the future with new augments
   - Data augmentation visualizations with --visualize_augments on the test images within `tests/data` (will be placed in the visualize folder in the future)
   - Random augment model creation with --aug_random_augments for debugging purposes (will be removed later)

2024-01-19 13:06 UTC, TimKoornstra requested changes
Ziet er goed uit :) Paar dingetjes die beter kunnen, maar verder ziet t er heel goed uit. Maarja ik heb t ook nog niet getest haha

2024-01-19 13:06 UTC, TimKoornstra commented on README.md
> +  - `--aug_invert`: Invert the pixels in the image
Ik zou die `--aug_` lekker weglaten, aangezien dat al eerder supported was. Dat scheelt weer mensen die zich afvragen wat er mis gaat met deze update & het is wel duidelijk dat dit augmentaties zijn

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/data_handling.py
> +        aug_binarize_otsu=args.aug_binarize_otsu,
zelfde als bij requirements.txt

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/generator.py
> +                 aug_random_crop=False,
.

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/loader.py
> +                        'aug_random_crop': self.aug_random_crop,
.

2024-01-19 13:06 UTC, TimKoornstra commented on src/model/management.py
> +from data.augment_layers import *
Liefst geen * imports gebruiken. Dit heeft meerdere redenen:

1. **Alles** wordt geimporteerd. Dit kan tot conflicten leiden als je in 2 files/imports dezelfde function/variable names hebt.
2. Lastig te lezen waar een functie vandaan komt voor mensen die je code base niet kennen.
3. Je hebt niet altijd een hele module nodig, wat kan leiden tot slechtere performance.

2024-01-19 13:06 UTC, TimKoornstra commented on src/model/management.py
> +        augment_selection = get_augment_model()
Je kunt het beste de args hier meegeven in plaats van in `augment_layers` opnieuw gaan getten. Dan doe je dat _en_ dubbel _en_ snap ik niet hoe de options en selections bepaald worden zonder naar die file te gaan.

2024-01-19 13:06 UTC, TimKoornstra commented on src/model/management.py
> +            logging.info("Augment visualizations are stored in the src folder")
Misschien dat je dit zelfs gewoon als een `if __name__ == "__main__"` onderaan deze file kunt zetten. Anders moet je steeds het hele script opstarten, etc. voordat je je kleine aanpassing kunt bekijken.

2024-01-19 13:06 UTC, TimKoornstra commented on src/model/management.py
> +            logging.info("Augment visualizations are stored in the src folder")
En t scheelt weer een arg ;)

2024-01-19 13:06 UTC, TimKoornstra commented on src/model/management.py
> +def save_augment_steps_plot(aug_model, sample_image_path, save_path, channels):
Waar zijn de type hints :( hieronder staan ze wel

2024-01-19 13:06 UTC, TimKoornstra commented on src/setup/arg_parser.py
> +    augmentation_args.add_argument('--aug_random_crop', action='store_true',
.

2024-01-19 13:06 UTC, TimKoornstra commented on tests/test_data_augments.py
Ik zou hier graag nog een aantal tests willen zien die verschillende combinaties van augments testen

2024-01-19 13:06 UTC, TimKoornstra commented on tests/test_datagenerator.py
Weinig tests, maar ik keur m goed omdat deze class toch binnenkort weg gaat

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +            fill_value=1,
Maar fill value is 1?

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +        Notes ----- - The `etf.deform_grid` function is used to apply the
oopsie

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +        # Apply "white" padding
Waarom niet zwart?

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +                "Invalid method. Supported methods are 'otsu' and 'sauvola'.")
Dit kun je beter in de init zetten

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +                         "Otsu for faster processing")
logging.warning

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +        inputs : object
2x parameters O.o

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +                                  constant_values=1)
waarom value 1?

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +    return augment_options
Ik weet niet wat ik vind van deze functie

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +    return augment_options
Globals kopiëren, etc. Waarom niet gewoon de lijst meegeven? En de naam is een beetje misleidend, het zouden eerder instances moeten zijn.

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +    args = get_args()
Gewoon args passen aan de functie. Dit is niet efficient en onhandig

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +                          augment_selection)
Ik denk dat het efficienter kan dan 2x door de lijst loopen. En de naam obj is een beetje vaag; misschien gewoon `layer`? of `aug_layer`?

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +    # Check if a blur occurs before binarization, if so replace with mild blur
Waarom?

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +                                     BlurImageLayer(mild_blur=True))
Werkt dit? Lijkt me niet dat je iets mag inserten in een lijst waar je op dat moment doorheen aan het loopen bent. Als het wel kan, lijkt me alleen maar dat er nare side-effects van zullen komen.

2024-01-19 13:06 UTC, TimKoornstra commented on src/data/augment_layers.py
> +                                     BlurImageLayer(mild_blur=True))
Misschien beter om de loop te doen met `for i, augment in enumerate(augment_selection[:]):`

2024-01-23 08:30 UTC, TimKoornstra approved these changes

2024-01-31 08:28 UTC, Thelukepet commented on src/model/management.py
> +from data.augment_layers import *
Eens, alleen heb ik binnen data.augment_layers altijd wel alle classes nodig die erin zitten. Normaliter probeer ik dit ook zo min mogelijk te gebruiken maar in dit geval kreeg ik anders een erg lelijke import met 9 classes

2024-01-31 08:33 UTC, Thelukepet commented on src/data/augment_layers.py
> +            fill_value=1,
Fout in comment, het moest 1 zijn

2024-01-31 08:35 UTC, Thelukepet commented on src/data/augment_layers.py
> +        # Apply "white" padding
Zwarte padding zorgt ervoor dat binarization kapot gaat omdat de functie dan de waardes van de padding meeneemt

2024-01-31 08:38 UTC, Thelukepet commented on src/data/augment_layers.py
> +                                  constant_values=1)
Ook weer vanwege binarization, zwarte padding zorgt voor problemen, uiteraard geen probleem als de operatie post-binarizatie wordt toegepast

2024-01-31 08:44 UTC, Thelukepet commented on src/data/augment_layers.py
> +    return augment_options
Ik pak specifiek de globals uit de file omdat ik dan zeker weet dat als er nieuwe layers zijn toegevoegd dat deze ook worden meegenomen. Dit is gedaan zodat ik niet telkens een lijst hoef up te daten, maar ik snap dat je een oplossing met een lijst logischer / beter te begrijpen vindt

2024-01-31 08:48 UTC, Thelukepet commented on src/data/augment_layers.py
> +    # Check if a blur occurs before binarization, if so replace with mild blur
Eerste twee lines zijn puur voor initialisatie, ik vervang de blur met een "milde blur" omdat anders het resultaat compleet onleesbaar wordt na binarisatie.

2024-03-05 08:06 UTC, merged